# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: berkeley.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x65rkeley.proto\"4\n\x11\x43onnectionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\"%\n\x12\x43onnectionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x0bTimeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\"-\n\x0cTimeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\x32m\n\x08\x42\x65rkeley\x12\x34\n\x07\x43onnect\x12\x12.ConnectionRequest\x1a\x13.ConnectionResponse\"\x00\x12+\n\nSyncClocks\x12\x0c.TimeRequest\x1a\r.TimeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'berkeley_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=18
  _globals['_CONNECTIONREQUEST']._serialized_end=70
  _globals['_CONNECTIONRESPONSE']._serialized_start=72
  _globals['_CONNECTIONRESPONSE']._serialized_end=109
  _globals['_TIMEREQUEST']._serialized_start=111
  _globals['_TIMEREQUEST']._serialized_end=157
  _globals['_TIMERESPONSE']._serialized_start=159
  _globals['_TIMERESPONSE']._serialized_end=204
  _globals['_BERKELEY']._serialized_start=206
  _globals['_BERKELEY']._serialized_end=315
# @@protoc_insertion_point(module_scope)
